(function (W) {
  W.stopwordsEN = [
    "a", "about", "above", "across", "after", "afterwards", "again", "against", "all", "almost",
    "alone", "along", "already", "also", "although", "always", "am", "among", "amongst", "amount",
    "an", "and", "another", "any", "anybody", "anyhow", "anyone", "anything", "anyway", "anywhere",
    "are", "around", "as", "at", "back", "be", "became", "because", "become", "becomes",
    "becoming", "been", "before", "beforehand", "behind", "being", "below", "beside", "besides", "between",
    "beyond", "both", "but", "by", "call", "came", "can", "cannot", "cant", "could",
    "couldn", "day", "did", "didn", "do", "does", "doesn", "doing", "don", "done",
    "down", "due", "during", "each", "either", "else", "elsewhere", "enough", "etc", "even",
    "ever", "every", "everybody", "everyone", "everything", "everywhere", "except", "few", "first", "for",
    "former", "formerly", "from", "front", "full", "further", "get", "give", "go", "going",
    "got", "had", "has", "hasn", "have", "haven", "having", "he", "hed", "hell",
    "her", "here", "hereafter", "hereby", "herein", "hereupon", "hers", "herself", "him", "himself",
    "his", "how", "however", "i", "id", "ie", "if", "ill", "im", "in",
    "inc", "indeed", "instead", "into", "is", "isn", "it", "its", "itself", "ive",
    "just", "keep", "kept", "know", "known", "last", "less", "let", "like", "little",
    "look", "made", "make", "makes", "many", "may", "maybe", "me", "meanwhile", "might",
    "mine", "more", "moreover", "most", "mostly", "much", "must", "my", "myself", "name",
    "namely", "near", "need", "neither", "never", "nevertheless", "next", "no", "nobody", "none",
    "noone", "nor", "not", "nothing", "now", "nowhere", "of", "off", "often", "on",
    "once", "one", "only", "onto", "or", "other", "others", "otherwise", "our", "ours",
    "ourselves", "out", "over", "own", "part", "per", "perhaps", "please", "put", "quite",
    "rather", "really", "regarding", "right", "said", "same", "saw", "say", "see", "seem",
    "seemed", "seeming", "seems", "seen", "serious", "several", "shall", "she", "shed", "shell",
    "should", "shouldn", "show", "side", "since", "six", "so", "some", "somebody", "somehow",
    "someone", "something", "sometime", "sometimes", "somewhere", "still", "such", "take", "ten", "than",
    "that", "the", "their", "theirs", "them", "themselves", "then", "thence", "there", "thereafter",
    "thereby", "therefore", "therein", "thereupon", "these", "they", "thing", "things", "think", "third",
    "this", "those", "though", "three", "through", "throughout", "thru", "thus", "till", "to",
    "together", "too", "top", "toward", "towards", "two", "under", "until", "up", "upon",
    "us", "use", "used", "using", "usually", "various", "very", "via", "want", "was",
    "wasn", "way", "we", "well", "went", "were", "weren", "weve", "what", "whatever",
    "whats", "when", "whence", "whenever", "where", "whereafter", "whereas", "whereby", "wherein", "whereupon",
    "wherever", "whether", "which", "while", "whither", "who", "whoever", "whole", "whom", "whose",
    "why", "will", "with", "within", "without", "won", "would", "wouldn", "yes", "yet",
    "you", "youd", "youll", "your", "youre", "yours", "yourself", "yourselves", "youve"
  ];
})(window.WC = window.WC || {});
