(function (W) {
  W.stopwordsDE = [
    "ab", "aber", "abermals", "alle", "allein", "allem", "allen", "aller", "allerdings", "alles",
    "allzu", "als", "also", "am", "an", "andere", "anderem", "anderen", "anderer", "anderes",
    "anders", "anstatt", "auch", "auf", "aus", "ausser", "ausserdem", "außer", "außerdem", "b",
    "bald", "bei", "beide", "beider", "beides", "beim", "beinahe", "bereits", "bevor", "bin",
    "bis", "bisher", "bist", "bitte", "bleibt", "bleiben", "blieb", "blieben", "bzw", "ca",
    "da", "dabei", "dadurch", "dafür", "dagegen", "daher", "dahin", "damit", "danach", "dann",
    "daran", "darauf", "daraus", "darin", "darüber", "darum", "darunter", "das", "dass", "daß",
    "dasselbe", "davon", "davor", "dazu", "dazwischen", "dein", "deine", "deinem", "deinen", "deiner",
    "deines", "dem", "demgemäß", "demgegenüber", "demselben", "demzufolge", "den", "denen", "denn", "dennoch",
    "denselben", "der", "derer", "derselbe", "derselben", "des", "desgleichen", "deshalb", "desselben", "dessen",
    "deswegen", "dich", "die", "dies",
    "diese", "dieselbe", "dieselben", "diesem", "diesen", "dieser", "dieses", "dir", "doch", "dort",
    "drauf", "drei", "drüber", "drum", "drunter", "du", "durch", "durchaus", "dürfen", "dürft",
    "durfte", "durften", "eben", "ebenso", "ehe", "eher", "ein", "eine", "einem", "einen",
    "einer", "eines", "einige", "einigem", "einigen", "einiger", "einiges", "einmal", "einst", "einzig",
    "er", "es", "etliche", "etwa", "etwas", "euch", "euer", "eure", "eurem", "euren",
    "eurer", "eures", "falls", "ferner", "folgende", "folgt", "für", "gab", "ganz", "ganze",
    "gar", "gegen", "gegenüber", "gehabt", "gehen", "geht", "gemäß", "genau", "gerade", "gesagt",
    "gestern", "gewesen", "gewiss", "geworden", "gibt", "gleich", "gleichwohl", "gut", "hab", "habe",
    "haben", "hat", "hatten", "hatte", "heißt", "her", "heraus", "herbei", "herein", "hierbei",
    "hierfür", "hierin", "hiermit", "hier", "hin", "hinab", "hinauf", "hinaus", "hinein", "hingegen",
    "hinter", "hoch", "ich", "ihm", "ihn", "ihnen", "ihr", "ihre", "ihrem", "ihren",
    "ihrer", "ihres", "im", "immer", "in", "indem", "indes", "infolge", "innerhalb", "ins",
    "inzwischen", "irgend", "ist", "ja", "je", "jeder", "jedem", "jeden", "jedenfalls", "jedoch",
    "jemals", "jemand", "jene", "jenem", "jenen", "jener", "jenes", "jetzt", "kam", "kann",
    "kannst", "kaum", "kein", "keine", "keinem", "keinen", "keiner", "keines", "keineswegs", "kommen",
    "konnte", "konnten", "können", "könnt", "könnte", "könnten", "lass", "lassen", "lässt", "leider",
    "lieber", "mache", "machen", "macht", "mal", "man", "manche", "manchem", "manchen", "mancher",
    "manches", "mehr", "mehrere", "mehrmals", "mein", "meine", "meinem", "meinen", "meiner", "meines",
    "meist", "meistens", "meisten", "mich", "mir", "mit", "mitten", "möchte", "möchten", "möglich",
    "mögen", "muss", "müssen", "müsst", "nach", "nachdem", "nachher", "nahm", "namens", "neben",
    "nehmen", "nein", "nicht", "nichts", "nie", "niemals", "niemand", "nirgends", "nirgendwo", "noch",
    "nun", "nur", "ob", "obgleich", "obwohl", "oder", "oft", "oftmals", "ohne", "paar",
    "recht", "sagte", "sah", "sahen", "schon", "sehe", "sehen", "sehr", "sei", "seid",
    "sein", "seine", "seinem", "seinen", "seiner", "seines", "seit", "seitdem", "selbst", "sich",
    "sie", "sieht", "sind", "so", "sodann", "sofern", "sofort", "sogar", "sogleich", "solche",
    "solchem", "solchen", "solcher", "solches", "soll", "sollen", "sollte", "sollten", "somit", "sondern",
    "sonst", "sowie", "sowohl", "soweit", "später", "statt", "stets", "tat", "taten", "trotz",
    "trotzdem", "tut", "über", "überall", "überdies", "überhaupt", "übrig", "übrigens", "um", "und",
    "uns", "unser", "unsere", "unserem", "unseren", "unter", "untereinander", "viel", "viele", "vielen",
    "vieler", "vieles", "vielleicht", "vielmehr", "vier", "vom", "von", "voneinander", "vor", "vorhin",
    "war", "warum", "was", "weder", "weg", "wegen", "weil", "weiter", "weiteren", "welche",
    "welchem", "welchen", "welcher", "welches", "wem", "wen", "wenig", "weniger", "wenn", "wer",
    "werde", "werden", "weshalb", "wessen", "wie", "wieder", "wieso", "will", "wir", "wird",
    "wirst", "wo", "woher", "wohin", "wohl", "wollen", "wollte", "wollten", "womit", "worüber",
    "würde", "würden", "zu", "zueinander", "zufolge", "zumal", "zumindest", "zur", "zurück", "zusammen",
    "zwar", "zwischen"
  ];
})(window.WC = window.WC || {});
